apiVersion: v1
kind: Secret
metadata:
  name: binwidthcalculator-secrets
  namespace: binwidthcalculator
type: Opaque
stringData:
  Jwt__SecretKey: "super-secret-key-that-is-32-characters!"
  Jwt__Key: "super-secret-key-that-is-32-characters!"